# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=b'/Users/tarun/code/jitterbunk/bunker/media/profilePics/default-profile-picture.png', upload_to=b'profilePics/'),
        ),
    ]
