# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0003_auto_20180622_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=b'../static/default-profile-picture.png', upload_to=b'profilePics/'),
        ),
    ]
