# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0005_auto_20180622_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='bunker.UserProfile'),
        ),
    ]
