# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0006_auto_20180626_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunker.UserProfile'),
        ),
    ]
