# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunker', '0007_auto_20180626_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userprofile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
